### ISSUE TITLE
Python 3.5 ConfigParser

### ISSUE THREAD

**Issue by jhunkeler** [spacetelescope/sphere#95]
```
+ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'
```

**Comment by pllim** [comment]
The fix is the same as spacetelescope/imexam#62

**Comment by larrybradley** [comment]
But it was already fixed here.  I can't reproduce this.

**Comment by pllim** [comment]
Oh yeah. Fixed in #87.

**Comment by jhunkeler** [comment]
https://github.com/spacetelescope/sphere/blob/v1.0.6/setup.py

We pull from tags, so it's not fixed. We need to make a 1.0.7 release.

**Comment by pllim** [comment]
Latest release is 1.0.10 but looks like you figured it out. 😄

**Comment by jhunkeler** [comment]
*recedes back into the darkness*
